# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Flöter
email: simon@floter.design
description: > # this means to ignore newlines until "baseurl:"
  Simon Floter is a Designer and Illustrator living in Amsterdam. He designs websites, logos, housestyles and draws pictures in exchange for money. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://floter.design" # the base hostname & protocol for your site
twitter_username: schweinedog
permalink: "/blog/:title"
collections:
  work:
    output: true
    permalink: /work/:path/
sass:
  style: compressed
# Build settings
markdown: kramdown